#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
python << END
import sys
import psycopg2
try:
    conn = psycopg2.connect(
        dbname="${POSTGRES_DB}", 
        user="${POSTGRES_USER}", 
        password="${POSTGRES_PASSWORD}", 
        host="${POSTGRES_HOST}", 
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
END
}
until postgres_ready; do
    >&2 echo "WAITING FOR POSTGRES"
    sleep 1
done
>&2 echo "!!!!POSTGRES IS UP!!!!"

exec "$@"



