#! /usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

working_dir = "$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

message_welcome "Welcome to the backup script for the ${POSTGRES_DB} database ......"

if [[ "${POSTGRES_USER}" == "postgres" ]]; then
    message_error "The ${POSTGRES_USER} user is not allowed to perform backups."
    exit 1
fi

export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

backup_filename = "${BACKUP_FILE_PREFIX}_$(date +%Y%m%d_%H%M%S).sql.gz"
pg_dump | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"

message_success "${POSTGRES_DB} database backup completed. File: ${backup_filename}. Placed in path ${BACKUP_DIR_PATH}."
