# Generated by Django 3.2.11 on 2023-03-08 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+811234567890', max_length=30, region=None, verbose_name='phone number')),
                ('about_me', models.TextField(default='Say something about yourself', max_length=500, verbose_name='about me')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=20, verbose_name='gender')),
                ('country', django_countries.fields.CountryField(default='JP', max_length=2, verbose_name='country')),
                ('city', models.CharField(default='Tokyo', max_length=180, verbose_name='city')),
                ('profile_photo', models.ImageField(default='/profile_default.jpg', upload_to='', verbose_name='profile photo')),
                ('twitter_handler', models.CharField(blank=True, max_length=50, verbose_name='twitter handler')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='profiles.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
